pipeline:
  docker:
    image: docker
    secrets:
      - docker_password
      - docker_username
    command:
      - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      - docker build -t jamesvmcewan/defuser-club
      - docker push jamesvmcewan/defuser-club
