pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: 206.189.26.21
    volumes:
      - ssh_volume
    key_path: /root/ssh/drone_rsa
    secrets:
      - ssh_volume
    script:
      - echo "test ssh"
