pipeline:
  docker:
    image: plugins/docker
    debug: true
    launch_debug: true
    repo: jamesvmcewan/defuser-club
    username: docker_username
    password: docker_password
    autotag: true
    secrets:
      - docker_password
      - docker_username
