pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: 206.189.26.21
    volumes:
      - '/root/drone_rsa:/root/ssh/drone_rsa'
    key_path: /root/ssh/drone_rsa
    script:
      - echo "test ssh"
