pipeline:
  gcr:
    image: plugins/gcr
    registry: eu.gcr.io
    repo: mcewan-io/defuser-club
    tags: latest
    secrets:
      - gcr_json_key
  server:
    image: appleboy/drone-ssh
    host: 206.189.26.21
    port: 22
    volumes:
      - '/root/id_rsa:/root/ssh/id_rsa'
    key_path: /root/ssh/id_rsa
    script:
      - server_cmd
      - exit
    secrets:
      - ssh_username
      - server_cmd
    when:
      branch: master
