pipeline:
  docker:
    image: docker
    commands:
      - 'echo ${DOCKER_USERNAME}'
      - 'echo ${DOCKER_PASSWORD}'
      - 'echo $${DOCKER_USERNAME}'
      - 'echo $${DOCKER_PASSWORD}'
    secrets:
      - docker_username
      - docker_password
