pipeline:
  docker:
    image: 'plugins/docker:17.12'
    debug: true
    launch_debug: true
    repo: jamesvmcewan/defuser-club
    username: docker_username
    password: docker_password
    autotag: true
    secrets:
      - docker_username
      - docker_password
