pipeline:
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG: true
    repo: jamesvmcewan/defuser-club
    username: docker_username
    password: docker_password
    autotag: true
    secrets:
      - docker_username
      - docker_password
