pipeline:
  gcr:
    when:
      branch: master
    image: plugins/gcr
    registry: eu.gcr.io
    repo: mcewan-io/defuser-club
    tags: latest
    secrets:
      - gcr_json_key
  ssh:
    when:
      branch: master
    image: appleboy/drone-ssh
    host: 206.189.26.21
    script:
      - cd server;./images.sh
    secrets:
      - ssh_key
      - ssh_username
